services:
  atm9:
    build:  # Use the DockerFile in the same directory as I am
      context: .
      dockerfile: DockerFile
      
      
    container_name: atm9

    ports:
      - "25565:25565"
  
    volumes:
    - ./Server:/server # Save data from host Server/ directory to container /server directory
    #- ./server_variables.txt:/run/secrets/server_variables:ro

    env_file:
    - server_variables.env

    restart: unless-stopped

  backup:
    build: 
      context: .
      dockerfile: DockerFile.backup
    
    container_name: atm9-backup

    depends_on: 
      - atm9
    #environment:
    #  RCON_PASSWORD: ${RCON_PASSWORD}

    volumes:
      - ./Server:/server:ro # :ro = read only
      - ./BackUps/:/BackUps
      #- ./server_variables.txt:/run/secrets/server_variables:ro

    env_file:
    - server_variables.env
    
    restart: unless-stopped