services:
  mcServer:
    build:  # Use the DockerFile in the same directory as I am
      context: .
      dockerfile: DockerFile
      
    container_name: mcServer

    ports:
      - "25565:25565"
  
    volumes:
    - ./Server:/server # Save data from host Server/ directory to container /server directory

    env_file:
    - server_variables.env

    restart: unless-stopped

  backup:
    build: 
      context: .
      dockerfile: DockerFile.backup
    
    container_name: atm9-backup

    depends_on: 
      - mcServer

    volumes:
      - ./Server:/server:ro # :ro = read only
      - ./BackUps/:/BackUps


    env_file:
    - server_variables.env
    
    restart: unless-stopped